version: '3'

services:
    
  redis-master:
    container_name: redis-master
    image: redis:latest
    command: redis-server --port 6379
    ports:
      - "6379:6379"
    volumes:
      - .:/app

  redis-slave:
    container_name: redis-slave
    image: redis:latest
    command: redis-server --slaveof redis-master 6379
    volumes:
       - .:/app

  sentinel-1:
    container_name: sentinel-1
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000

  sentinel-2:
    container_name: sentinel-2
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000

  sentinel-3:
    container_name: sentinel-3
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000

  app:
    container_name: python-app
    build: .
    image: pyredis
    command: python -u app.py
    depends_on:
      - redis-master
      - redis-slave

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"

#  redis-sentinel-1:
#    container_name: redis-sentinel-1
#    image: redis:latest
#    command: redis-server /app/sentinel1.conf --sentinel --protected-mode no
#    volumes:
#       - .:/app
#    links:
#      - redis-master:redis-master
#      - redis-slave
#    ports:
#      - "26379:26379"
#
#  redis-sentinel-2:
#    container_name: redis-sentinel-2
#    image: redis:latest
#    command: redis-server /app/sentinel1.conf --sentinel --protected-mode no
#    volumes:
#       - .:/app
#    links:
#      - redis-master:redis-master
#      - redis-slave
#    ports:
#      - "26379:26379"
#
#  redis-sentinel-3:
#    container_name: redis-sentinel-3
#    image: redis:latest
#    command: redis-server /app/sentinel1.conf --sentinel --protected-mode no
#    volumes:
#      - .:/app
#    links:
#      - redis-master:redis-master
#      - redis-slave
#    ports:
#      - "26379:26379"
