{
 "title": "System stats",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_cache{id=\"/\",instance=\"cadvisor:8080\",job=\"cadvisor\"}",
     "legendFormat": "Cached memory"
    },
    {
     "expr": "container_memory_max_usage_bytes{id=\"/\",instance=\"cadvisor:8080\",job=\"cadvisor\"}",
     "legendFormat": "Max usage"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{id=\"/\",instance=\"cadvisor:8080\",interface=\"eth0\",job=\"cadvisor\"}",
     "legendFormat": "Bytes received"
    },
    {
     "expr": "container_network_transmit_bytes_total{id=\"/\",instance=\"cadvisor:8080\",interface=\"eth0\",job=\"cadvisor\"}",
     "legendFormat": "Bytes transmitted"
    },
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "CPU metrics",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_cpu_user_seconds_total{id=\"/\",instance=\"cadvisor:8080\",job=\"cadvisor\"}",
     "legendFormat": "CPU user seconds"
    },
    {
     "expr": "container_cpu_load_average_10s{id=\"/\",instance=\"cadvisor:8080\",job=\"cadvisor\"}",
     "legendFormat": "CPU load average"
    },
    {
     "expr": "container_cpu_system_seconds_total{id=\"/\",instance=\"cadvisor:8080\",job=\"cadvisor\"}",
     "legendFormat": "CPU system seconds"
    }
   ]
  }
 ]
}